### ISSUE TITLE
Unexpected server response when I'm following the tutorial

### ISSUE THREAD

**Issue by lee-brown** [mixer/client-node#100]
Hi, 

I've tried to follow the node tutorial here:
https://dev.mixer.com/guides/chat/chatbot.html

and I'm getting this as a response:

> Socket error
> Error: unexpected server response (400)
>     at ClientRequest.response (C:\node_modules\ws\lib\WebSocket.js:719:15)
>     at Object.onceWrapper (events.js:277:13)
>     at ClientRequest.emit (events.js:189:13)
>     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
>     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
>     at TLSSocket.socketOnData (_http_client.js:442:20)
>     at TLSSocket.emit (events.js:189:13)
>     at addChunk (_stream_readable.js:284:12)
>     at readableAddChunk (_stream_readable.js:265:11)
>     at TLSSocket.Readable.push (_stream_readable.js:220:10)

This is my code (minus the token)
https://gist.github.com/lee-brown/a2332fd8861c156a5987c1b22667eae8

Is this an issue with the node client/api or is it a problem with my code? Any help would be greatly appreciated thank you!

**Comment by lee-brown** [comment]
Just to add on to this issue, I get exactly the same error when I literally copy and paste the code on the tutorial which has my authenication token.

**Comment by hairyhum** [comment]
I have the same issue. Is there a workaround other than just use plain websockets?
