### ISSUE TITLE
Node.JS (TypeScript) @mixer/client-node Issue.

### ISSUE THREAD

**Issue by NicmeisteR** [mixer/client-node#109]
This sample code for NodeJS:

`
client.use(new Mixer.OAuthProvider(client, {
    tokens: {
        access: '{{ token here }}',
        expires: Date.now() + (365 * 24 * 60 * 60 * 1000)
    },
}));
`

Is outputting the below error.

`
Argument of type '{ tokens: { access: string; expires: number; }; }' is not assignable to parameter of type 'IOAuthProviderOptions'.
  Property 'clientId' is missing in type '{ tokens: { access: string; expires: number; }; }' but required in type 'IOAuthProviderOptions'.ts(2345)
OAuth.d.ts(14, 5): 'clientId' is declared here.
`

Am I doing something wrong or is there a issue with the type declarations for TypeScript?

**Comment by NicmeisteR** [comment]
To remove the error message I removed:
`    getRequest(): {
        headers: {
            [key: string]: string;
        };
    };`

In the OAuth.d.ts file  and added a clientId filed on the client.use

**Comment by NicmeisteR** [comment]
Essentially making the **clientId** field in the **IOAuthProviderOptions** interface and by removing the broken getRequest() function fixed the issue, I will add a merge request.

**Comment by NicmeisteR** [comment]
https://github.com/mixer/client-node/pull/110

**Comment by ProbablePrime** [comment]
Hey ClientID is a required property. This error just means that you haven't provided it.
 If you provide it this should go away.
