### ISSUE TITLE
Auto Ping Not Checking Connection State

### ISSUE THREAD

**Issue by artdude543** [mixer/client-node#47]
As the websocket class handles the pinging to the chat server. It should be checking if the socket is open before trying to ping. Otherwise if the socket is closed `ws` will throw an error about is being closed. Which with promises you can handle this; But as the class will reject or "kill" the chat connection if it does not get a pingback (within time) so it can be reconnected. I think the class should check and if closed then run the code for the safe closing etc..

**Comment by artdude543** [comment]
Even though this may not needed but we have it anyway. [Stack track for the error occuring](https://logs.exozone.net/share/issue/31362e363736/).

**Comment by nickangelou** [comment]
I've seen the same issue occurring. Any updates would be greatly appreciated.

Reference: https://github.com/websockets/ws/issues/337

**Comment by artdude543** [comment]
@nickangelou if you wanted you could give this module a try: [mixer-chat](https://github.com/ExoZoneDev/mixer-chat) contains many fixes and some optimisations.

**Comment by ProbablePrime** [comment]
With akamai GTM and various other improvements I will close this issue. If it reoccurs please re-open
