### ISSUE TITLE
404 Package not found

### ISSUE THREAD

**Issue by enapupe** [mixer/client-node#79]
It seems you don't have this package published yet..

npm ERR! 404 Not Found: @mixer/client-node

https://www.npmjs.com/package/@mixer/client-node

 Should I be using `beam-client-node` instead?

**Comment by SReject** [comment]
Yes this repo is for `beam-client-node`.  

Mixer was originally named beam.pro. NPM does not allow packages to be renamed due to versioning(That is, projects that make use of `beam-client-node` in their package.json would break if it were renamed)

**Comment by enapupe** [comment]
Yeah but that's not what the readme says:

<img width="530" alt="screen shot 2018-07-20 at 10 54 36" src="https://user-images.githubusercontent.com/291082/43006140-53452156-8c0b-11e8-875f-073663df89af.png">

**Comment by SReject** [comment]
Thats an inconsistancy on their part.

**Comment by connor4312** [comment]
Thanks for opening the issue! We're now published as [@mixer/client-node](https://www.npmjs.com/package/@mixer/client-node).

**Comment by enapupe** [comment]
Thanks!
