### ISSUE TITLE
The NPM package just doesn't have anything

### ISSUE THREAD

**Issue by theLMGN** [mixer/client-node#82]
![](http://lmgn.uk/J2ZV9u.png)

**Comment by ProbablePrime** [comment]
Thank you for your report I am taking a look

**Comment by ProbablePrime** [comment]
![](https://i.probableprime.co.uk/180825-ipg7i6kcgxOpUqrxdy53.png)

I am not able to reproduce this error.

**Comment by theLMGN** [comment]
@ProbablePrime I'm running npm 6.2.0 on macOS HS 10.13.6

**Comment by connor4312** [comment]
Yea, the npm bundle definitely has stuff in there. Probably some local issue or a partial installation.

![](https://peet.io/i/18-08-d2dc0937-3896-4bdd-b9a4-5bf201bc84b2.png)
